# Generated by Django 5.1.2 on 2025-01-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_about_me_user_avatar_user_birthday_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+70000000000', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
