# Generated by Django 5.1.2 on 2025-02-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
