# Generated by Django 5.1.2 on 2025-03-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_publickey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_auth',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
